version: '1'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client
    volumes:
      - ./logs:/app/logs
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    depends_on:
      - server
    network_mode: "service:server"