FROM ubuntu:22.04
WORKDIR /app
COPY client/client.py requirements.txt ./
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    libgl1 \
    libgl1-mesa-glx \ 
    libglib2.0-0 \
    libxcb1 \
    libxkbcommon-x11-0 \
    libgtk2.0-dev \
    pkg-config \
    x11-apps \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt
RUN mkdir -p /app/logs
CMD ["python3", "client.py", "--host", "localhost", "--port", "8080"]